name: Lint comparison

on: [pull_request]

jobs:
  lint_comparison:
    runs-on: ubuntu-latest
    outputs:
      report: ${{ steps.comparison.outputs.report}}
    steps:
    # install python
    - uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    # checkout the PR
    - uses: actions/checkout@v3
      with:
        ref: "refs/pull/${{ github.event.number }}/merge"
    # cache the pip step for speed
    - uses: actions/cache@v3
      with:
        path: ${{ env.pythonLocation }}
        key: ${{ env.pythonLocation }}-${{ hashFiles('setup.py') }}
    # install the dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .[testing]
    # build the comparison report
    - id: comparison
      uses: SJShaw/pylint-compare/build-report@v3
      with:
        targets: antismash *.py
        install_pylint: false
    - name: Save lint report
      run: |
        mkdir -p ./lint_report
        echo "${{ steps.comparison.outputs.report }}" >> ./lint_report/message
        echo "${{ github.event.number }}" >> ./lint_report/pr
    - uses: actions/upload-artifact@v7
      with:
        name: lint_report
        path: lint_report/
